name: MinTic Delete AWS CloudFormation Stack

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
    - name: MinTic Checkout and download repository
      uses: actions/checkout@v3

    - name: MinTic Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: MinTic Delete EC2
      run: |
        aws cloudformation delete-stack \
          --stack-name TestCfEC2
        
        echo "Waiting for stack deletion to complete..."
        aws cloudformation wait stack-delete-complete \
          --stack-name TestCfEC2
        
        echo "Stack deleted successfully!"

    - name: Delete S3
      run: |
        aws cloudformation delete-stack \
          --stack-name TestCfS3
        
        echo "Waiting for stack deletion to complete..."
        aws cloudformation wait stack-delete-complete \
          --stack-name TestCfS3
        
        echo "Stack deleted successfully!"